#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config left_padding	 8
bspc config right_padding	 8
bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

feh --bg-fill ~/Pictures/background.jpeg
polybar -q top -c ~/.config/polybar/cuts/config.ini &
polybar -q bottom -c ~/.config/polybar/cuts/config.ini &
urxvt
